name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q

  trivy_scan:
    name: Container vulnerability scan (Trivy)
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container image
        run: |
          docker build -t fireping:ci .

      - name: Trivy (human-readable table)
        uses: aquasecurity/trivy-action@0.24.0
        continue-on-error: true
        with:
          scan-type: 'image'
          image-ref: 'fireping:ci'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Run Trivy container scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'image'
          image-ref: 'fireping:ci'
          format: 'sarif'
          output: 'trivy-results.sarif'
          # Only fail on CRITICAL vulns that have fixes available
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          exit-code: '1'

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'


